name: Multi-arch images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: pocketbase
            file: docker/Dockerfile.pocketbase
          - name: server
            file: docker/Dockerfile.server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build linux/amd64 and linux/arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: esp32-${{ matrix.name }}:local
